### PR TITLE
API: Add types for parameters of gym-university-bladeburner API

### LINKED ISSUE #1581: ns.sleeve.setToBladeburnerAction does not provide the list of actions in the method signature
Recording this issue for Venusaur based on the discussion on the discord suggestions channel
https://discord.com/channels/415207508303544321/415213435974975508/1273346517679472731

Currently setToBladeburnerAction  does not offer any help as to what strings are valid actions:

image

Compare this to sleeve.travel():
image

A type could be added to the NetscriptDefinitions file similar to CityName
https://github.com/bitburner-official/bitburner-src/blob/dev/src/ScriptEditor/NetscriptDefinitions.d.ts#L7797

Note that this type should probably be also copied and used in the code that handles the actual sleeve code:
https://github.com/bitburner-official/bitburner-src/blob/dev/src/PersonObjects/Sleeve/Sleeve.ts#L482

### PR DESCRIPTION
**Pull request by catloversg**
This PR is much bigger than normal because it renames Bladeburner-related enums. I decide to rename them because:
- `BladeX` -> `BladeburnerX`: Players can be confused because it's not obvious that "Blade" means "Bladeburner".
- Enums' keys: camelCase -> PascalCase: I want the keys to be consistent among Bladeburner-related enums. BladeBlackOpName's keys are PascalCase, but the others are camelCase. When I check all of our enums, there are more enums that use PascalCase than camelCase, so I decide to use PascalCase.

This kind of renaming is not mandatory, and I don't have a strong opinion about it. I can revert them if the maintainers want.

I played for a while with Bladeburner and did not see any problem.

Closes #1581.

### CODE REVIEW

**Comment by d0sboots** [comment]
It's big, but mechanical (-only) changes are easy to review. I saw Snarling gave OK in discord.

**Comment by d0sboots** [comment]
Rolled back, somehow you missed some stuff that got through the PR tests (merge issue?)

**Comment by Snarling** [comment]
Yeah it was due to some content from #1475 also needing name changes from this PR

**Comment by d0sboots** [comment]
That makes sense, usually we can blindly trust the presubmit results (to at least accurately reflect the postsubmit results, not to catch all errors XD), but for a change this large there is greater risk of conflicts that aren't merge conflicts, especially when I like to merge a bunch of things at once.

**Pull request merged**
