### PR TITLE
PROGRAMS: Change flight.exe to easily display unmet requirements

### PR DESCRIPTION
**Pull request by TheAimMan**
Thought it might be nice to add visual confirmation to the flight requirements.  Change the logic to display the message in warning text if the requirement hasn't been met.  If it has been met, display in primary text.

Example:
image

Easy to tell at a glance what has been completed and what has not

### CODE REVIEW

**Comment by jjclark1982** [comment]
The `[x]` checklist style used on the milestones page could also help with readability here.

**Comment by TheAimMan** [comment]
I like your idea better.  I didn't want to do colors as I was concerned about color blindness or custom interfaces, but decided to use the already existing tools that colored text.

**Comment by TheAimMan** [comment]
image

**Comment by jjclark1982** [comment]
Ooh, that looks great.

**Pull request merged**
