### PR TITLE
IPVGO: Fix API documentation

### LINKED ISSUE #1149: Manually unborking Go API documentation until it's unborked
https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.go.md

The markdown is messed up, but I'm not sure how I would fix the source code, so here's a temporary thing that I can read while someone gets to fix it.

Looks like the code block (which someone made with triple backticks) broke the table; any literal line breaks in the markdown source code made the markdown parser think it should end the table.

----

[Home](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/index.md) &gt; [bitburner](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.md) &gt; [Go](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.go.md)

## Go interface

IPvGO api

**Signature:**

```typescript
export interface Go 
```

## Properties

|  Property | Modifiers | Type | Description |
|  --- | --- | --- | --- |
|  [analysis](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.go.analysis.md) |  | { getValidMoves(): boolean\[\]\[\]; getChains(): (number \| null)\[\]\[\]; getLiberties(): number\[\]\[\]; getControlledEmptyNodes(): string\[\]; } | Tools to analyze the IPvGO subnet. |
|  [cheat](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.go.cheat.md) |  | { getCheatSuccessChance(): number; removeRouter( x: number, y: number, ): Promise&lt;{ type: "invalid" \| "move" \| "pass" \| "gameOver"; x: number; y: number; success: boolean; }&gt;; playTwoMoves( x1: number, y1: number, x2: number, y2: number, ): Promise&lt;{ type: "invalid" \| "move" \| "pass" \| "gameOver"; x: number; y: number; success: boolean; }&gt;; repairOfflineNode( x: number, y: number, ): Promise&lt;{ type: "invalid" \| "move" \| "pass" \| "gameOver"; x: number; y: number; success: boolean; }&gt;; destroyNode( x: number, y: number, ): Promise&lt;{ type: "invalid" \| "move" \| "pass" \| "gameOver"; x: number; y: number; success: boolean; }&gt;; } | Illicit and dangerous IPvGO tools. Not for the faint of heart. Requires Bitnode 14.2 to use. |

## Methods

|  Method | Description |
|  --- | --- |
|  [getBoardState()](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.go.getboardstate.md) | <p>Retrieves a simplified version of the board state. "X" represents black pieces, "O" white, and "." empty points. "\#" are dead nodes that are not part of the subnet. (They are not territory nor open nodes.)</p><p>For example, a 5x5 board might look like this:</p><code>   [</code><br /><code>      "XX.O.",</code><br /><code>      "X..OO",</code><br /><code>      ".XO..",</code><br /><code>      "XXO.#",</code><br /><code>      ".XO.#",</code><br /><code>   ]</code><br /><p>Each string represents a vertical column on the board, and each character in the string represents a point.</p><p>Traditional notation for Go is e.g. "B,1" referring to second ("B") column, first rank. This is the equivalent of index \[1\]\[0\].</p><p>Note that the \[0\]\[0\] point is shown on the bottom-left on the visual board (as is traditional), and each string represents a vertical column on the board. In other words, the printed example above can be understood to be rotated 90 degrees clockwise compared to the board UI as shown in the IPvGO subnet tab.</p> |
|  [getOpponent()](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.go.getopponent.md) | Returns the name of the opponent faction in the current subnet. |
|  [makeMove(x, y)](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.go.makemove.md) | Make a move on the IPvGO subnet gameboard, and await the opponent's response. x:0 y:0 represents the bottom-left corner of the board in the UI. |
|  [passTurn()](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.go.passturn.md) | <p>Pass the player's turn rather than making a move, and await the opponent's response. This ends the game if the opponent passed on the previous turn, or if the opponent passes on their following turn.</p><p>This can also be used if you pick up the game in a state where the opponent needs to play next. For example: if BitBurner was closed while waiting for the opponent to make a move, you may need to call passTurn() to get them to play their move on game start.</p> |
|  [resetBoardState(opponent, boardSize)](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.go.resetboardstate.md) | <p>Gets new IPvGO subnet with the specified size owned by the listed faction, ready for the player to make a move. This will reset your win streak if the current game is not complete and you have already made moves.</p><p>Note that some factions will have a few routers on the subnet at this state.</p><p>opponent is "Netburners" or "Slum Snakes" or "The Black Hand" or "Daedalus" or "Illuminati",</p> |

### PR DESCRIPTION
**Pull request by catloversg**
Triple backticks cause trouble when we use `api-documenter`. This PR fixes it.

`<br/>` and 2 space characters after it (`  `) are intentional.
- `<br/>` create a line break.
- 2 space characters after `<br/>` create a line break when viewing in VS Code. IntelliJ IDEA does not need these ones.

Fixes #1149.

Alternative fix:
```
   * For example, a 5x5 board might look like this:
   *
   *[
   *
   *  "XX.O.",
   *
   *  "X..OO",
   *
   *  ".XO..",
   *
   *  "XXO.#",
   *
   *  ".XO.#",
   *
   *]
   *
   * Each string represents a vertical column on the board, and each character in the string represents a point.
```
This alternative fix makes the space between each line look too big, so I don't use it.

Main fix:
screenshot1

Alternative fix:
screenshot2

### CODE REVIEW

**Comment by d0sboots** [comment]
This looks totally good, but I was too slow on it so it needs to be rebased now.

**Comment by catloversg** [comment]
@d0sboots I rebased it. The usage of `<pre lang="javascript">` in d81358c80f1ef37321b7ef13dc1ba3855d57905c is just a temporary fix. It does not show the line break properly on GitHub and IDE(s).

**Comment by User670** [comment]
#1142 fixed it. You probably could close this now unless you want your version to replace that.

**Comment by catloversg** [comment]
@User670 As I said, this PR provides the proper fix.

**Pull request merged**
