### PR TITLE
MISC: Gang Expenses category in MoneySource

### PR DESCRIPTION
**Pull request by deansvendsen**
New MoneySource 'gang-expenses' added.  Gang-based purchases (augs and weapons) are now directed to it.

CATEGORY: MISC

API function NS.getMoneySources() now includes 'gang_expenses' in its returned dictionary.  A minor QoL edit to get my feet wet.

### CODE REVIEW

**Comment by TheAimMan** [comment]
You need to modify
`test\jest\__snapshots__\FullSave.test.ts.snap`
to include the new stat, as part of the testing suite is comparing an already existing save snapshot to one made with the changes in the PR.
You can run the test locally with 'npm run test' before committing the change to github.

**Comment by deansvendsen** [comment]
Thanks for the advice.  I'll open a new PR when I've got the i's and t's dotted and crossed, so to speak.

**Comment by d0sboots** [comment]
I don't think you need to close this one... just fix up the test and push that on this branch.

**Comment by deansvendsen** [comment]
Okay, well, the test code has been modified and runs clean, and I've pushed it to my origin.  All yours.

And thanks for the advice.  I'm sorta running with training wheels here ;)

**Comment by Sphyxis** [comment]
May also want to add the gang costing here to allow the user to see it.
src\ui\CharacterStats.tsx

Also, you should add it to src\ScriptEditor\NetscriptDefinitions.d.ts  in the interface MoneySource  so it gets passed to the user when ns.getMoneySources is called.

**Comment by deansvendsen** [comment]
Goddamn, I *swear* I'd done the changes in NetscriptDefinitions.d.ts.  I'm going senile.  The CharacterStats.tsx changes are a good idea, tho.

**Comment by Snarling** [comment]
Looks good, nice work!

**Pull request merged**
