### PR TITLE
REMOTE: add 'getAllServers' method to RFA

### PR DESCRIPTION
**Pull request by shyguy1412**
this is the same as PR #960 I just moved branch

### CODE REVIEW

**Comment by LJNeon** [comment]
Seems like the check failed due to a really strange error?

**Comment by d0sboots** [comment]
I tried rerunning it, but it's persistent.

**Comment by LJNeon** [comment]
Wait is there a leading space in the title? That might be causing it.

**Comment by shyguy1412** [comment]
Good catch! I totally didn't see that, removed now

**Comment by LJNeon** [comment]
@d0sboots can you rerun it one more time?

**Pull request merged**
