### PR TITLE
HASHNET: Little boost for the extreme late game.

### PR DESCRIPTION
**Pull request by Zelow79**
+1 MaxServers fills out the max servers page evenly. 
+3 MaxCache is nice for extreme late game.

Save file info:
-Brand new with just SF 1.1
-Currently in BN9.1
-Dev tools to get max money and purchase all servers and max out all their upgrades. This should be the rate with no external modifers.

image

### CODE REVIEW

**Comment by Snarling** [comment]
We just merged a different huge BN9 buff... Probably just gonna close this one out.

**Comment by Zelow79** [comment]
> We just merged a different huge BN9 buff... Probably just gonna close this one out.

The one that enables the free hashnet server in the first install only? I'm not arguing the decision and fine with it if this doesn't feel like a fit, but the 2 shouldn't effect each other really. These changes would only really effect very late game if not a post BN clearing state. I can ways take another crack at this type of a PR later though. Not like there was too much modified. Just a couple values changed.

**Comment by Snarling** [comment]
So let me just explain some of my frustration.

Part of the problem with a Player-contributor based game is that almost every submitted PR that touches on balance is a buff. Small buff to this, small buff to that, make this easier, etc. And then it's almost impossible to ever maintain challenge in the game because no one is ever willing to nerf anything, and buffs just keep rolling in.

Like for instance, you had these two buffs to hacknet in the queue, and then also a buff in the form of new and better high-end augments for grafting, we recently buffed sleeve shock recovery, we added stuff to make batching timing easier which is a buff, etc. I don't remember the last time anything was made more challenging (other than "mandatory coffeeparty" for corp which got reverted because of constant complaints from players). Luckily we have a corporation overhaul in the works that should fix some of the imbalance for that mechanic.

It's exhausting seeing nothing but buffs get pushed through when it's like, the game is the easiest it's ever been. So I know as a player you don't ever think "wow you know what would be cool, if X was harder" but always making things easier isn't actually good game design. 

Personally, I would have preferred merging this one (less impactful on balance, most of the impact is at the end of a node anyway) and closing out the other (a 100-level starting server is a *huge* buff to BN9 IMO), but it is what it is.

**Comment by Zelow79** [comment]
> So let me just explain some of my frustration.
> 
> Part of the problem with a Player-contributor based game is that almost every submitted PR that touches on balance is a buff. Small buff to this, small buff to that, make this easier, etc. And then it's almost impossible to ever maintain challenge in the game because no one is ever willing to nerf anything, and buffs just keep rolling in.
> 
> Like for instance, you had these two buffs to hacknet in the queue, and then also a buff in the form of new and better high-end augments for grafting, we recently buffed sleeve shock recovery, we added stuff to make batching timing easier which is a buff, etc. I don't remember the last time anything was made more challenging (other than "mandatory coffeeparty" for corp which got reverted because of constant complaints from players). Luckily we have a corporation overhaul in the works that should fix some of the imbalance for that mechanic.
> 
> It's exhausting seeing nothing but buffs get pushed through when it's like, the game is the easiest it's ever been. So I know as a player you don't ever think "wow you know what would be cool, if X was harder" but always making things easier isn't actually good game design.
> 
> Personally, I would have preferred merging this one (less impactful on balance, most of the impact is at the end of a node anyway) and closing out the other (a 100-level starting server is a _huge_ buff to BN9 IMO), but it is what it is.

I guess I can see a lot of what you mean here. Regarding hashnet and BN9 specifically I wouldn't say they're hard anyways, it's just a lot of waiting. Imo slower != harder either. Which is why I would call it a QoL improvement more than a buff, but I can see how it's seen as a buff too. Knowing this though, I can look more into nerfing rather than buffs. It's just hard to consider nerfs, because they're easier to be seen negatively if the change effected someone's favorite aspect I think. Comparatively there is a few features that feel like they haven't received the same love as other features I guess too. So I find myself more incentivised to try to breathe new life into it. Also, my original BN9 change would have been a nerf in a way too. I was trying to raise WD difficulty and production rate of hash to make hashnet stand out more. It was mentioned that it would make hashnet feel different than what they could normally expect, but then again that's pretty much every feature with BN modifiers nerfing their functions in other nodes.

Going forward I will take what you have mentioned here and consider it. The last thing I wanted was to cause you any frustration or be a burden. Sorry about that.

**Comment by Snarling** [comment]
No need to apologize, it's natural as a player who is contributing to focus on "adding cool new stuff" which typically means buffing. I appreciate that you're contributing.

**Pull request closed without merging**
