### PR TITLE
UI: add Run button to the Script Editor

### PR DESCRIPTION
**Pull request by bezrodnov**
https://github.com/bitburner-official/bitburner-src/assets/5138959/eebb18de-963e-4e4c-b835-6eeeff4b3d0b

### CODE REVIEW

**Comment by d0sboots** [comment]
I like it!

**Review by Snarling — COMMENTED** [review]
* There's no type validation that it's a script being ran, you're just asserting that whatever is being edited is a valid script name 
image
* It's weird that it uses the terminal but doesn't. It doesn't care about the currently connected server on the terminal, so having the terminal display a message for it is weird
* There's no feedback if the script failed to run, until you navigate to the terminal to investigate

**Comment by bezrodnov** [comment]
good points!
need some time to figure out the best approach for each

**Comment by Snarling** [comment]
Closing since this is still in draft / there were unresolved concerns and this hasn't had any activity in a couple months.

**Pull request closed without merging**
