### PR TITLE
INFRA: Update Webpack to @latest, along with other dev packages

### LINKED ISSUE #185: Deprecated dependencies
- [x] `html-webpack-plugin`: 3.x is no longer supported
  - [ ] `asar`: Please use @electron/asar moving forward.  There is no API change, just a package name change
  - [ ] `electron-notarize`: Please use @electron/notarize moving forward.  There is no API change, just a package name change
  - [ ] `electron-osx-sign`: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
  - [ ] `w3c-hr-time`: Use your platform's native performance.now() and performance.timeOrigin.
  - [ ] `chokidar`: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
  - [ ] `querystring`: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
  - [ ] `fsevents`: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
  - [ ] `uuid`: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  - [ ] `source-map-resolve`: See https://github.com/lydell/source-map-resolve#deprecated
  - [ ] `resolve-url`: https://github.com/lydell/resolve-url#deprecated
  - [ ] `urix`: Please see https://github.com/lydell/urix#deprecated
  - [ ] `source-map-url`: See https://github.com/lydell/source-map-url#deprecated

### PR DESCRIPTION
**Pull request by d0sboots**
### MERGE

Fixes #185 

until we're reasonably certain that 2.2 is settled. I'm 85% confident that this doesn't break anything, but I don't want to take that 15% chance while a quick change might be needed.

This updates Webpack to the latest version, along with the following dev packages:

- webpack-cli
- webpack-dev-server
- mini-css-extract-plugin
- babel-loader
- react-refresh
- @pmmmwh/react-refresh-webpack-plugin
- html-webpack-plugin

Most of the extra packages were needed to get webpack working without warnings, a few were opportunistic to get rid of `npm audit` warnings. We're down to 4 "moderate" issues now. Also, the binary size is down, probably due to webpack improvements and/or a new browserslist requiring fewer polyfills.

I intentionally kept the set of updated packages small, to try and avoid breakage/unintended consequences. In particular, Electron will be updated in a different PR.

### Testing
- Dev server works
- `ns.rainbow` works (testing crypto change)
- Achievements list works
- `npm run build` works
- `npm run test` works
- `format` and `lint` still work
- Electron still builds and the binary still works properly (I had to make a few small tweaks to the scripts to get it working on my machine)

### CODE REVIEW

**Comment by Snarling** [comment]
Awesome!

What were the changes you had to make to get electron to build properly? `npm run build` followed by `npm run electron` should build the electron packages, but I see `npm run electron` is broken right now.

edit: Actually I got the electron command to run again by just changing the electron command back to `"sh ./tools/package-electron.sh"`. Without the sh, it tells me `'.' is not recognized as an internal or external command, operable program or batch file.`

**Comment by d0sboots** [comment]
What environment are you running in? I needed to *remove* the sh to get `npm run electron` to work properly, since the script does not run properly under sh (it requires bash).

**Comment by d0sboots** [comment]
K, hopefully this should work for you while still working for me. Also, the lint failure isn't real.

**Comment by Snarling** [comment]
> What environment are you running in? I needed to _remove_ the sh to get `npm run electron` to work properly, since the script does not run properly under sh (it requires bash).

I am using git bash on windows (it was one of the options to install with GitHub Desktop).

This is great by the way. No more errors about vulnerabilities, and vendor.bundle.js is a lot smaller too.

**Pull request merged**
