### PR TITLE
DOCS: Adding information to CONTRIBUTING.md that I wish I knew for my first PR.

### PR DESCRIPTION
**Pull request by deansvendsen**
No code changes, just additions to CONTRIBUTING.md

### CODE REVIEW

**Comment by deansvendsen** [comment]
I'm appreciating the irony here - an edit to a document saying to use 'npm run format' on your checking fails for it's lack.  :)
At least I know to run it on both code and docco now.

**Comment by deansvendsen** [comment]
Well, I am beyond confused as to why this edit is failing its tests.  fyi, tests pass on my end (npm run test), and git status reports my branch is up to date with origin.

**Comment by d0sboots** [comment]
It is a mystery to me as well.

**Comment by Caldwell-74** [comment]
maybe Math.random() returned the 0 or smt to small? 
grafik

**Comment by Snarling** [comment]
Yeah looks like the test failure was just a weird fluke. Test passes after rerunning. Test might need to be updated to avoid this edge case.

**Pull request merged**
