### PR TITLE
BUGFIX: Use mathjax from npm, rather than vendored copy.

### LINKED ISSUE #313: Cleanup dist/ext folder
Mathjax is still into dist/ext folder

### LINKED ISSUE #1489: Corporation - Changing component formula Math Renderer option crashes game
Changing the Math Renderer from CHTML to SVG causes the game to crash. After changing this option, the game will crash on startup every time due to missing file attempting to be loaded on startup.

To Reproduce:
Right-clicking on the component formula in the Corporation tab and follow the context menu -> Math Settings -> Math Renderer selecting SVG.
bitburner_mathrender_bug1

BitBurner v2.6.2 (633da3830) (July 03 2024 last updated).

Error message indicates trying to load a file named "svg.js" but the full path to file is not included in error prompt.
bitburner_mathrender_bug2

Digging through SteamDB history, looks like this file was included in older MathJax libraries (last found in 3.2.0) but is not included in the MathJax-3.2.2 library any more.
bitburner_mathrender_bug3

Can be resolved by creating an empty file in the MathJax-3.2.2 library for svg.js. Component formulas still render, and allows game to launch and change renderer back to CHTML.
bitburner_mathrender_bug4

### PR DESCRIPTION
**Pull request by tomprince**
Fixes #1489. Closes #1490. Fixes #313.

We have a dependency on mathjax anyway, so rather than vendor all the files from mathjax, we can just grab them as part of the build process from `node_modules`.

### CODE REVIEW

**Comment by d0sboots** [comment]
OMG, it didn't even occur to me that these might be checked in to source control, since they're in `dist/` and also that's insane.

**Comment by tomprince** [comment]
Tested this with electron, and it doesn't work there, due to paths being slightly different between the devserver and electron. I suspect this is an easy fix though.

**Comment by d0sboots** [comment]
Not at my computer ATM, but I was planning on looking this over carefully (the build artifacts) before merging.

**Comment by tomprince** [comment]
Fixed so it works in both electron and the dev server. I did this by adjusting the path the dev server uses for copied files to match what gets built.

**Comment by tomprince** [comment]
From https://github.com/bitburner-official/bitburner-src/pull/1490#issuecomment-2231373538
> The things in the base directory (named mml-svg.js, etc.), are bundle files. We only need/want the one we are using (tex-chtml.js), since they are large and only usable by explicitly mentioning them in a script tag or similar.

Assuming this is correct, I've adjusted the copy plugin's configuration to only copy `tex-chtml.js` from the base directory, and copy everything in subdirectories. It is easy enough to tweak this further, but I'm inclined to not try to optimize more than this for the first step.

**Comment by d0sboots** [comment]
I had some unrelated yaks to shave, but eventually I was able to verify that this is working for both dev builds and the full electron build, and switching to SVG mode works OK.

**Pull request merged**
