### PR TITLE
COMPANY: Clarify job listings and requirements

### LINKED ISSUE #20: Working-for-companies mechanic has poor UI and documentation
[macdjord]
The gameplay mechanic whereby you can work for a company & get promoted is almost entirely undocumented and has a non-discoverable, unclear GUI:

- The fact that you can get a promoted by applying for the job you already have is not obvious and not explained anywhere
- The fact that there even *is* a career ladder to advance up is not immediately obvious
- Hovering over one of the job application buttons tells you the minimum stat requirements for that job (or, of you already have a job on that career track, for the next promotion level). However, if the player already meets the stat requirements for a more senior position in that same career track, they will skip directly to the most-senior position they qualify for. Nothing in the UI tells you this is going to happen, or even notifies you that it *has* happened when it does.
- The career tracks are not documented anywhere. ('So, I'm a Senior Software Engineer now? How many more steps does that mean I have to make CTO?')
- Nothing explains what player stats the different career tracks depend on when calculating reputation gain and salary (so that the user can pick the one most in line with their current build)
- There's a quit button, but no explanation of why you might need it. You can hold jobs at multiple companies at once, there's no obligation involved in holding a job (e.g. you aren't forced to work a shift every day), and if you do quit you can reapply and get your job back instantly at, AFAICT, no penalty. The only purpose I can maybe see for it is leaving the CIA or NSA so you can join one of the criminal factions?
  - I think it would be more interesting if you *couldn't* join a criminal faction after being employed by one of the agencies, and conversely could not join the agencies if you're part of those factions; if you wish to switch, you must wait until the next reset. Currently, the only mutually-exclusive choice is which city-based faction to join on each reset.

**Comments From Original Issue**

[Kebap]
> Small improvements for point 1 and 2 maybe change button from "Apply for X" to "Promote in X" if you already hold that title and there is a promotion available (no matter if you fulfill the criteria yet) so players actually are shown a difference and can find more info with mouse-over.

[devnuhl]
> Related to hovering and having information with a mouse-over, I just encountered the mouse-over information being irrelevant to my current position / next promotion. I know my current position because it's at the top.
> Screenshot 2022-10-03 161952
> 
> The hover shows the basic position info, which it has not shown for the last several promotions, but the correct values. Attempting the promotion, though, says I'm ineligible because I lack the stats/rep I need. I'm guessing the tooltips may have been copy/pasted, and this one missed getting updated to the appropriate numbers?
> 
> Screenshot 2022-10-03 162008
>

### LINKED ISSUE #708: Corp Job requirements missleading
When applying for Corp job, the reputation requirement is misleading,
Both in tooltip and in the error message the reputation requirement will say 40000.
In the Corp info it will say 38.678k 

Reputation requirement should be formatted the same way the info is formatted: 40.000k

Steps to reproduce:
1. apply for a software job in a corp you never worked for
2. work a bit
3. go back to the job screen, hover over "apply for Software Job" button
4. see the tooltip requirement says reputation 8000 required. Should say 8.000k required
5. click the "apply for Software Job" button
6.  see the error message requirement says reputation 8000 required. Should say 8.000k required

Bitburner v2.4.0 (fc86895c3)

job_requirements_1
job_requirements_2

### LINKED ISSUE #856: Mismatched promotion requirements for IT Job and Software Job
Step to reproduce:
1. Apply for IT Job for a mega-company.
2. Repeat promotion until certain Job Title is obtained.
3. Check the hint of promotion requirements.

Result:
  Hint shows the basic applying requirements of IT Job:
image

  However the actual requirements are shown in the hint of Software Job:
image
image

Version: Bitburner v2.5.0 (b87b8b4be)

### PR DESCRIPTION
**Pull request by jjclark1982**
### Original Problem

The "Apply to Job" buttons are an ongoing source of confusion. The displayed job fields do not match the actual jobs the company offers or the actual promotion tracks that they follow. The job you see the requirements for is sometimes different from the one you effectively apply for. There is no indication when you have reached the end of a job track.

Fixes #20 (except for removing the "Quit" button)

Fixes  #708

Fixes #856

Fixes this problem reported on discord:

> derpygamer2142:
> not sure if this is a bug but there's a little empty box here if you get to the max level
> apply-to-job

### PR Description

This PR adds tooltips to "Apply for Job" buttons showing a checklist of requirements.

Instead of showing "Apply for [field] Job" buttons for each of several hard-coded fields, this shows the specific jobs available at the company.

### Balance changes:
- The secret rep bonus to faction requirements for backdooring a company server now also applies to job requirements.
- Part-time jobs have removed the penalty for doing something else simultaneously.
- Previously hidden jobs like Network Engineer and Business Consultant are now available through the UI.

### API changes:
- `ns.singularity.applyToCompany()` now returns the name of the job received (or null if none). Compatible with the previous boolean return value.

### Screenshots of new UIs:
No requirements
Screenshot 2023-11-29 at 12 31 20 PM

Overqualified
Screenshot 2023-11-29 at 12 28 34 PM

Qualified
Screenshot 2023-11-29 at 12 28 41 PM

Underqualified
Screenshot 2023-11-29 at 12 28 50 PM

Listing at a small company
Screenshot 2023-11-29 at 7 31 29 PM

Listing at a medium-size company
Screenshot 2023-11-29 at 12 32 43 PM

Listing at a large company
Screenshot 2023-11-29 at 12 29 12 PM

https://github.com/bitburner-official/bitburner-src/assets/208776/2e1533d5-4ae8-4252-85c3-6ad3d57c5611

https://github.com/bitburner-official/bitburner-src/assets/208776/cbfccdcf-80c7-49c0-969d-7695943badfa

### CODE REVIEW

**Comment by jjclark1982** [comment]
Showing a tooltip with the title of the job being applied for helps explain away some of the ambiguity mentioned in #856 , but it calls more attention to the ambiguity of automatically getting multiple promotions. 🤔 

Screenshots of development progress:
Screenshot 2023-11-12 at 2 02 31 PM
Screenshot 2023-11-12 at 2 13 16 PM
Screenshot 2023-11-26 at 6 13 42 PM
Screenshot 2023-11-12 at 1 26 01 PM
Screenshot 2023-11-26 at 9 02 42 PM
Screenshot 2023-11-12 at 2 04 34 PM

**Comment by jjclark1982** [comment]
Using the same structured requirements as factions means that backdooring a company's server will also give a bonus to rep needed for promotions. I reckon this is good gameplay as it allows faster progression for lower-level jobs in exchange for automating more backdoors, but has little effect on high level jobs.

Bonus amount: 100,000 rep  
Promotion requirements: 8,000 - 3,200,000 rep

**Comment by jjclark1982** [comment]
We can resolve most of the ambiguity about the difference between the job you apply for and the job you get by showing a tooltip preview of the highest available job in a category instead of the lowest.

For example, if you are qualified for both "CEO" and "CTO", you can see both of their requirements on their respective buttons. And it is also more clear that both "IT Job" and "Software Job" feed into "CTO".


https://github.com/bitburner-official/bitburner-src/assets/208776/bb87c132-3c63-44ec-82f0-76bb391ca543

**Comment by draughtyan** [comment]
related to: https://github.com/bitburner-official/bitburner-src/issues/20

Perhaps "Apply for XYZ job" could change to "Apply for promotion in XYZ" when you have a job in that career path?

**Comment by jjclark1982** [comment]
> Perhaps "Apply for XYZ job" could change to "Apply for promotion in XYZ" when you have a job in that career path?

Thanks, that's related and I can address it here. I also see that there is currently no way to apply for a "Network Engineer" job at companies that have them.

**Comment by jjclark1982** [comment]
Concept: show a list of all job positions the company offers, disabling the ones you are underqualified for and fading the ones you are overqualified for. This makes it easy for the player to scroll and scan for the highest qualified job in a track.

Screenshot 2023-11-28 at 12 43 48 PM

**Comment by jjclark1982** [comment]
By only showing the "Apply" button on jobs you are qualified for, we can eliminate the possibility of triggering confusing job-track-merges from the UI.

Screenshot 2023-11-28 at 6 33 48 PM

Screenshot 2023-11-28 at 8 59 32 PM

**Comment by Kelenius** [comment]
That looks overcomplicated, I think the version in the first post is better.

**Comment by Snarling** [comment]
Yeah I agree that the verbose display is a bit much, especially when many of the job locations have other things you can do at that location other than applying for jobs.

**Comment by jjclark1982** [comment]
(marked as draft pending finalization of API changes in #953)

**Comment by jjclark1982** [comment]
I tried showing the complete job listing as a modal in [36baa63](https://github.com/bitburner-official/bitburner-src/pull/927/commits/36baa633eeeca58ce2a0c7f9cb304dc3c6d18b4a), but it is still pretty intimidating.

Showing simple buttons with detailed tooltips for only the immediately available jobs:

Screenshot 2023-12-17 at 11 03 47 PM

**Comment by Snarling** [comment]
Looks great. I thought it might be weird to remove the job "fields" from the UI, but I think it turned out nicely, and lets us mostly get rid of that whole system which was poorly implemented.

"JobField" still exists and is used for the purposes of ns.singularity.applyToCompany, but we should probably just deprecate that and make an `ns.singularity.applyForJob(companyName, jobName)` which would be way more usable with the rest of the API anyway.

The only real critique I have is that the UI doesn't really show what the requirements are for a direct promotion from your current position. So e.g. as an IT Intern at ECorp limited by reputation, I don't know how much rep I should have before checking back for that promotion, because I can't see the requirements until I already meet them. Showing every out-of-reach job isn't necessary, but the immediate promotion should be shown.

That said I'm gonna go ahead and merge this, looks like a quick followup PR should be pretty easy since you have JobListings.tsx laid out very simply

**Pull request merged**
