### PR TITLE
CORPORATION: remove TA Modal and integrate TA toggles into Sell Modal

### PR DESCRIPTION
**Pull request by Caldwell-74**
remove the extra Modal for setting TA's and integrate them into the Sell Modal
image
image
image

ill try to include some more explanations into the Sell Modal about TA

### CODE REVIEW

**Comment by myCatsName** [comment]
You're kind of an asshole treating me and my ideas the way you did then jumping onto the first chance you find to add some toggles of your own.

**Comment by Caldwell-74** [comment]
okay first of all i didnt "jump" on this
we had someone having an issue yesterday with the annoying TA string wich i made a fix for
while i was testing it i had to jump between the modals to toggle TA's
something i havent done in a long time (i have a script)
iam currently trying to fix all the small things at corps that many complain about but just no one took the time to write a pr 
secondly  i didnt "add" toggles i moved them from one modal to another to get rid of an unnecessary page switch
a page switch that was the reason for the annoying string (a signal for a setting that isnt interacted with on that modal)
and lastly iam fine with you blocking me i did block you too
iam also fine with working in a productive/constructive manner with you but from here on ill just ignore messages that contain personal attacks

you are taking this WAY too personally

**Comment by myCatsName** [comment]
>you are taking this WAY too personally

Familiar invalidation phrase.

Denying your perception. Minimizing your feelings. Trying to control how long you feel something, or judging you for how you feel it.

**Comment by Caldwell-74** [comment]
this is not the right place for this kind of stuff 

but anyway sure a conflict is made out of 2 person atleast and i was one of them but the fact that you continued the same issue further and further even after you blocked me and i blocked you with others even with the main dev
might indicate that your role in this is a bit bigger than what you admit

**Comment by myCatsName** [comment]
From the same list of common invalidation techniques, you continue.

Turning things around. Trying to get you to question yourself. Trying to isolate you

**Comment by myCatsName** [comment]
> the fact that you continued the same issue further and further

And from the same list Talking about someone like they aren't there. You continued on as soon as I blocked you. Can't take a hint to let the conversation chill and notice its affecting one of your peers. You hurt me. You cared so much about that bullshit that you sacrificed someone you worked with.

**Pull request closed without merging**
