### PR TITLE
AUGMENTS: 2 new combat and 1 new charisma augmentations.

### PR DESCRIPTION
**Pull request by Zelow79**
3 new graft only augmentations. They're scaled to match modifiers with Hydroflames Left Arm and cost with QLink. 

Names, descriptions, costs, faction/grafting can all be open to debate. I would like these to match stat weights with Hydros Left Arm if possible, but other than than I just had to come up with the rest as I went. I didn't slack on it by any means, but if anyone has a better name or description, cost, etc that can all be tweaked. I am proud of some of what I came up with (you will know :D) and even got some input from the discord on a few things too.

Here are the augments.
Mughur's Eyes
image
image

Ultra Auto Reflex Chip
image
image

Silver Tongue
image
image

### CODE REVIEW

**Comment by Mughur** [comment]
If `Mughur's Eyes` force the number format to be exponential form then I'll allow this

**Comment by Zelow79** [comment]
> If `Mughur's Eyes` force the number format to be exponential form then I'll allow this

Does that count if it is already a setting in the options?
image

**Comment by Mughur** [comment]
no, it only counts if after installing it the `Use exponential form instead of suffixed form` becomes toggled on and toggling it off becomes disabled.

**Comment by Zelow79** [comment]
> no, it only counts if after installing it the `Use exponential form instead of suffixed form` becomes toggled on and toggling it off becomes disabled.

Umm, I am sure I could implement this, but I am unsure how Snarling might feel about that lol.

**Comment by Snarling** [comment]
For the exponential display thing, that's fine, just let me review the implementation on that.

Could use some work on these aug descriptions, they are extremely immersion-breaking, which isn't the case even for augs named after users. Meme/nonserious descriptions may be something you enjoy but it's something I'd like to avoid.

e.g. here's some descriptions of existing username augs:

Hydroflame Left Arm
```
The left arm of a legendary BitRunner who ascended beyond this world.
It projects a light blue energy shield that protects the exposed inner parts.
Even though it contains no weapons, the advanced tungsten titanium
alloy increases the user's strength to unbelievable levels.
```

Z.O.E
```
Zoë's Omnicerebrum Ënhancer for sleeves inserts an omnicerebrum into your sleeve.
An omnicerebrum is a near perfect simulation of the human brain, allowing it to take advantage of a larger variety of augments. 
But you should know about this BitRunner, since you have one of these yourself!
```

phyzical WKS harmonizer
```
A copy of the WKS harmonizer from the MIA leader of the Shadows of Anarchy
injects *Γ-based cells that provides general enhancement to the body.
```

Also typos (e.g. "you no longer have to thank"), but probably not relevant if the descriptions need reworked.

**Comment by Zelow79** [comment]
> For the exponential display thing, that's fine, just let me review the implementation on that.
> 
> Could use some work on these aug descriptions, they are extremely immersion-breaking, which isn't the case even for augs named after users. Meme/nonserious descriptions may be something you enjoy but it's something I'd like to avoid.
> 
> e.g. here's some descriptions of existing username augs:
> 
> Hydroflame Left Arm
> 
> ```
> The left arm of a legendary BitRunner who ascended beyond this world.
> It projects a light blue energy shield that protects the exposed inner parts.
> Even though it contains no weapons, the advanced tungsten titanium
> alloy increases the user's strength to unbelievable levels.
> ```
> 
> Z.O.E
> 
> ```
> Zoë's Omnicerebrum Ënhancer for sleeves inserts an omnicerebrum into your sleeve.
> An omnicerebrum is a near perfect simulation of the human brain, allowing it to take advantage of a larger variety of augments. 
> But you should know about this BitRunner, since you have one of these yourself!
> ```
> 
> phyzical WKS harmonizer
> 
> ```
> A copy of the WKS harmonizer from the MIA leader of the Shadows of Anarchy
> injects *Γ-based cells that provides general enhancement to the body.
> ```
> 
> Also typos (e.g. "you no longer have to thank"), but probably not relevant if the descriptions need reworked.

Thank you for the feed back. I genuinely missed that typo on the reflex chip, but I did attempt to go over the wording a bit looking for them. I did and as I mentioned in the PR description it's all open to debate. For clarities sake though, are you saying all three need to be looked over again? If any of the three where acceptable which ones? Also, is Mughurs the only one you would consider extremely immersion-breaking? I'm assuming the "Minecraft and Hockey" part, I guess it is sort of an inside joke on the Discord, but probably my favorite part haha.

Assuming I need to do a full redesign, I think I'd like to do all 3 in dev/moderator tribute style. Mughur do you have any preferences on your augment? Different part, name, description you would like? Also, does anyone have a nomination for the other 2? I was thinking Snarling was another good pick, since he's been doing such an awesome job maintaining already, but I don't know if I feel we know each other well enough to write a good description or name for it. So all suggestions are welcome. I love the technical stuff and suck when it comes to lore haha.

**Comment by Snarling** [comment]
I think the Ultra Auto Reflex Chip is definitely the closest to acceptable, the other two are not really describing what is being augmented. But I still don't really get it, the second sentence doesn't make sense to me. What does auto-replying / thinking about what to say have to do with boosting dexterity? The reflexes+conversational reflexes thing would make more sense if it was e.g. a dex+cha combined aug.

Also something to consider is that these are "ultimate" level augs, the cream of the crop for their particular stat. They don't necessarily need to be super-verbose (e.g. the QLink description is pretty short), but a player should be able to read the description and have it make sense in-world that this thing is giving them +180% agility or whatever.

Previously in the past, hydro has asked major contributors to design their own augs with descriptions, I never really got around to coming up with a design for one since I didn't want it to be something boring like +xxx% to stat. Also I'm not great at making these flavorful cyberpunk-style descriptions either.

**Comment by Zelow79** [comment]
Closing this for now at least, I lack the creativity or the patients to sit down and come up with better alternatives for the descriptions. Too bad it will have to be back burner'd for such a reason.

**Pull request closed without merging**
