### PR TITLE
DEVMENU: Fix bug in Time skip menu

### LINKED ISSUE #795: "Time skip" in the development menu does not actually skip time
To reproduce this, just enable the development menu, select "Time skip" , and any of the offered choices. This saves and reloads the game, but the message at the start of the game says that just a few seconds have passed. This also means that generating hashes for testing purposes is, as far as I know, not really feasible.

Happens in v2.4.1 (https://github.com/bitburner-official/bitburner-src/commit/de5ebc993bb20634c3f601631017970c8924dc50), for example, but also dev (https://github.com/bitburner-official/bitburner-src/commit/f95ca64e016553d3352525fcab365e7f5523dc27).

bug-skip-time

I've looked a bit into this and found that SaveObject.saveGame() gets called twice. The first time, Player.lastUpdate hat the decreased value which implements the time skip. When it gets called the second time, however, the value is the current time again. This call apparently comes from the auto save feature.

Since I'm not familiar with the code and the architecture, I don't know what the proper fix would be. I tried just removing the saving and reloading part in the time skip which worked fine in my case, i.e. the game catches up and calculates the hashes gained in the selected time as expected. However, I had a basically fresh game without any scripts running, and I expect performance to be quite poor this way.

For your reference, I have added a stack trace of the two calls to SaveObject.saveGame(). Also see this diff that removes the save+reload after selecting a time skip:
```
diff --git a/src/DevMenu/ui/TimeSkip.tsx b/src/DevMenu/ui/TimeSkip.tsx
index 37a7c8a36..fdafdbb94 100644
--- a/src/DevMenu/ui/TimeSkip.tsx
+++ b/src/DevMenu/ui/TimeSkip.tsx
@@ -18,8 +18,6 @@ export function TimeSkip(): React.ReactElement {
     return () => {
       Player.lastUpdate -= time;
       Engine._lastUpdate -= time;
-      saveObject.saveGame();
-      setTimeout(() => location.reload(), 1000);
     };
   }
```

[localhost-1694268863124.log](https://github.com/bitburner-official/bitburner-src/files/12566009/localhost-1694268863124.log)

### PR DESCRIPTION
**Pull request by catloversg**
This PR fixes a bug in the Time skip menu. The root cause is the autosave feature. The flow:
- `Player.lastUpdate` and `Engine._lastUpdate` are decreased in `TimeSkip.tsx`. [Step 1]
- Engine loop in `Engine.start` runs. It calculates `diff`, **set `Engine._lastUpdate` and `Engine._lastUpdate` to current time** (minus a small offset), then call `Engine.updateGame(diff)`. [Step 2]
- `Engine.updateGame` calls `Engine.decrementAllCounters`.
- `Engine.decrementAllCounters` decreases `Engine.Counters.autoSaveCounter`.
- `Engine.updateGame` calls `Engine.checkCounters`.
- `Engine.checkCounters` checks `Engine.Counters.autoSaveCounter`. `Engine.Counters.autoSaveCounter` is very likely negative at this point, especially if we skip 1 hour/day. Autosave happens, and it saves `Player.lastUpdate` of step 2 (current time), not step 1.

The fix is simple. We only need to counter the decrement of `Engine.Counters.autoSaveCounter`.

Fixes #795.

### CODE REVIEW

**Comment by d0sboots** [comment]
Is autoSaveCounter part of the saved state? This strikes me as rather a hack, although this is a dev menu feature so that might be OK. But if it has the possibility of permanently delaying autosave, I'm not a fan...

The best fix IMO is to fix the interactions in step 2. I feel like it has the possibility of causing *actual* bugs, such as missing offline updates, not just for this feature.

**Comment by d0sboots** [comment]
OK, thinking about it some more I don't think the issue is actually in step 2 at all.

I think the problem is that we are letting `Engine.updateGame` run at all. Basically, there are two possible ways time skip could work, and currently we are doing neither of them:
* We could skip time in an offline fashion. This would involve adjusting `lastUpdate` and *immediately* saving the game. This should then show offline progress when the page reloads.
* We could skip time in an online fashion. This would involve adjusting `lastUpdate` and *never reloading the page*. The normal engine updates will handle applying the time jump.

Right now, we're doing the 2nd but pretending it's like the first.

**Comment by d0sboots** [comment]
OK, I've figured out the *actual* issue with #795. It's a real bug in the code, which causes a small amount of hash loss every time you load, but it's only really noticeable in this usecase.

**Comment by d0sboots** [comment]
See #1223. I think all that remains here is to sort out the reload/no-reload issue.

**Comment by catloversg** [comment]
Let's deal with it in #1223.

**Pull request closed without merging**
