### PR TITLE
BUGFIX: Fix additionalMsec overflow issue

### LINKED ISSUE #940: additionalMsec delay overflow
https://discord.com/channels/415207508303544321/415213413745164318/1176573161727340625

https://github.com/bitburner-official/bitburner-src/blob/6a76e1a9ab58d9b6f103c90793307c61a668334f/src/Netscript/NetscriptHelpers.tsx#L379

setTimeout ends immediately for numbers >= 2**31

### PR DESCRIPTION
**Pull request by d0sboots**
Closes #940 

Also refactors H/G/W to use a helper method for `HGWOptions`, like it should have from the beginning.

### CODE REVIEW

**Comment by nanogyth** [comment]
Similar changes needed for grow and weaken
https://github.com/bitburner-official/bitburner-src/blob/6a76e1a9ab58d9b6f103c90793307c61a668334f/src/NetscriptFunctions.ts#L265
https://github.com/bitburner-official/bitburner-src/blob/6a76e1a9ab58d9b6f103c90793307c61a668334f/src/NetscriptFunctions.ts#L372

**Comment by nanogyth** [comment]
Maybe a helper function for parsing/verifying additionalMsec, instead of helper.number

**Comment by d0sboots** [comment]
Ugh I blithely assumed it *was* in the helper because it was in NetcriptHelpers.ts

**Comment by d0sboots** [comment]
OK, fixed that, although it involved some refactoring (that should have already been done).

**Comment by Snarling** [comment]
Rebasing and then merging this FYI

**Pull request merged**
