### PR TITLE
REFACTORING: ScriptEditor

### PR DESCRIPTION
**Pull request by bezrodnov**
REFACTORING: ScriptEditor

### CODE REVIEW

**Comment by bezrodnov** [comment]
Hi guys :)

I've spent a couple of hours tonight to refactor the ScriptEditorRoot.tsx and stuff around it a bit.
I'm not yet fully satisfied with the results, but it's already looking better imho.
I've quickly tested the game after these changes locally (start:dev, in browser) and haven't found obvious bugs so far.

Why am I doing this - I wanted to clean up this part of the app a bit before actually fixing the issue with tabs #554.

I hope my efforts won't get lost and that you will help me with the PR review and testing

**Comment by d0sboots** [comment]
I looked it over at a high level; seems like a good change to me. ScriptEditorRoot was definitely getting too large.

I probably would have passed a few more props around rather than making a full-blown context, especially since this component hierarchy is pretty shallow, but I won't say it was the wrong call. There are definitely other places where a context would help matters.

Snarling will probably have other thoughts.

**Comment by Snarling** [comment]
I also haven't done any testing yet, but just from an organizational standpoint I don't really have any issues with this. I agree that the ScriptEditorRoot was way too big and cluttered before, so the reorganization is warranted.

One gripe I do have just from the initial scan of the changes is I am not a fan of that useBoolean hook. setValue(false) and setValue(true) are already very clear / not confusing, and when someone unfamiliar with this custom hook sees it in use with it's slightly odd declaration usage, I believe it will cause more confusion than it solves.

**Comment by bezrodnov** [comment]
@Snarling `useBoolean` hook is pretty straightforward and is very easy to get used to.
I agree that it looks very simple and basic. The main benefit it provides is that  `on`, `off` and `toggle` functions are wrapped in `useCallback` which is very convenient when you want to use them in `useEffect`, `useMemo` or in another `useCallback`.

It also looks nice in some situations, e.g.
```tsx
const MyComp = () => {
  const [isDialogOpen, { on: openDialog, off: closeDialog }] = useBoolean(false);
  ...
  return (
    <>
      ...
     <MyButton onClick={openDialog}>Open Dialog</MyButton>
     ...
     <MyDialog open={isDialogOpen} onClose={closeDialog} />
    </>
  )
```

Another point: one of the relevant "rules" I use in react is - wrap in `useCallback` functions passed down to child elements. This way child elements have the option to avoid unnecessary re-renders, establish effects, optimize performance with useMemo etc. It does not have to be used always, but I almost always do this in react contexts cause these props are accessible to every descendant. And this is where `useBoolean` hook comes in handy.

The first time I saw this hook I was also a bit skeptical (it was added by my colleague). But after giving it a try in a few projects at work I personally found it useful. And other colleagues were also happy to use it.

If you are still not convinced, I can easily remove it. In this case I'll add `useCallback`s right inside the context which will make it a bit less readable.

**Comment by Snarling** [comment]
`React guarantees that setState function identity is stable and won’t change on re-renders. ` https://legacy.reactjs.org/docs/hooks-reference.html#usestate

~~As far as I can tell there is no reason to useCallback on a setState function. useCallback would be for ensuring that a function not created by a react hook is also stable and does not change between rerenders (or only changes based on a dependency list). There are some places in our code where it would be useful, but not for wrapping a setState function.~~

Edit: Actually I can see what you mean, in many cases we are not passing the setState function directly, but instead passing a new anonymous function that sets a particular state, and that would not remain stable. Feel free to keep it in.

**Comment by Snarling** [comment]
Seems good, and I was not able to get anything to break in testing.

**Pull request merged**
