### PR TITLE
UI: Sidebar performance optimizations

### LINKED ISSUE #238: SidebarRoot can take >50ms to render, and rerenders every 200ms
- Steps to reproduce
  - Open the profiling tab and take a profile. The sidebar will clearly appear as a large timesink, although it might not be as dramatic if you have a faster PC.
- Bitburner v2.1.0 (8f4636cb), probably all earlier versions

Needless to say, this severely impacts things like batching that depend on stable timing.

I am actively working on this issue.
Sidebar Slow

### PR DESCRIPTION
**Pull request by G4mingJon4s**
# UI: Sidebar performance optimizations

### Status
Not ready for merge. Needs bug fixing (see Added Bugs) and has possible improvements (see Possible future improvements).

### Current optimizations
- Changed `ListItem` of type `button` to `ListItemButton` . The button value of `ListItem` is deprecated.
- Moved some calculated values into `useMemo` hooks.

### Effects
Moving some calculations inside `useMemo` hooks reduced the scripting time from an average of 4ms to about 1ms.
Changing the `ListItem` to `ListItemButton` reduced the overall time down to an average of 18ms.

### Possible future improvements
All of the functions for calling the router functions don't need to be re-defined and could be moved outside of the function.
Not sure if that would be a good idea, maybe post your opinion about that

### Added bugs IMPORTANT
Changing the buttons, added unexpected space around the button. My css is not that great, so I'll leave that to someone else.

### Linked issues

Closes #238

### Formatting
- [X] lint
- [X] format

### CODE REVIEW

**Comment by Snarling** [comment]
A couple things to note so far:

1. This already needs a rebase and it will also conflict with #241 which will get merged once its own conflicts have been resolved.
2. Based on #238 and discord comments, I'm pretty sure @d0sboots was already working on a PR to address this (with #241 as the base), so that will also conflict with this. We will most likely have to merge one of them and then manually add any other useful stuff from the one that wasn't merged that was missing in the one we did. @d0sboots can you submit your WIP PR and just mark it as a draft? This would make it much clearer that work is in progress on something.
3. For material UI imports, I believe it's recommended to import from the specific component's file, instead of from the main `@mui/material`, to reduce bundle size.

**Comment by d0sboots** [comment]
I'll go ahead and add mine as a draft. It's the same idea as this one, but more extensive and without visible changes. If we want to change ListItem for ListItemButton after, it'll be a much smaller change on top of mine.

**Comment by d0sboots** [comment]
#246

**Comment by G4mingJon4s** [comment]
Closing. Changes already in #246

**Pull request closed without merging**
