### PR TITLE
BN: CHARITY

### PR DESCRIPTION
**Pull request by Sphyxis**
Created a new PR with a single change.

### CODE REVIEW

**Comment by d0sboots** [comment]
Just a note: You don't/didn't have to create a new PR, anything you do on your branch will be reflected in the PR. Although if you do rebases, you typically need to force-push.

**Comment by Snarling** [comment]
@d0sboots 
I know on the other branch, squashing enough commits to make rebasing sane was giving me issues due to an error about not being able to squash merge commits. I think that's why @Sphyxis made this whole new branch out of the changes from the first branch, now it should be easier to rebase this one as needed.

**Comment by Sphyxis** [comment]
That's exactly why I did that.  I'm still learning github though and didn't realize I just had to change the fork on the PR.

**Comment by Sphyxis** [comment]
Link:   https://sphyxis.github.io/bitburner-src/

**Pull request closed without merging**
