### PR TITLE
REMOTE: add 'getAllServers' method to RFA

### PR DESCRIPTION
**Pull request by shyguy1412**
# Description

In the Discord server it was discussed that it would be useful if the RFA had access to a full list of servers + their root access status
this change adds that method to the RFA

### CODE REVIEW

**Comment by LJNeon** [comment]
Looks like the prettier check failed.

**Comment by Semanual** [comment]
@shyguy1412 run `npm run format` and push again

**Comment by shyguy1412** [comment]
I am closing this and reopening on another branch cause I made this pr is blockin the dev branch for me x.x

**Comment by d0sboots** [comment]
Ah yes, it is best to have each PR on its own branch.

**Pull request closed without merging**
