### PR TITLE
MISC: Increase minimum Node version

### PR DESCRIPTION
**Pull request by catloversg**
There is no need to support older Node versions.

Tested: Windows 10 - Node v20.11.1 and Node v18.20.4.

### CODE REVIEW

**Comment by catloversg** [comment]
Our CI workflow is using Node.js 16.13.1. We should update them to v20: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/.

@d0sboots If you agree, I'll make another PR to do that.

**Comment by d0sboots** [comment]
Hehe, I think you'll have to upgrade the CI *first*, before we can merge this XD

**Comment by catloversg** [comment]
@d0sboots #1578 was merged. We can merge this one now.

**Comment by d0sboots** [comment]
Even though it doesn't show anything to merge, I think you need to `git pull`/merge the updated git workflows into your branch so that the tests will pass - they're still using the old versions.

Given the nature of this, I don't want to submit without everything being green.

**Pull request merged**
